In [5]:
import pandas as pd
df = pd.read_csv('C://Users//aksha//Desktop//Projects//SINS_PROJECT//dataset//TWTR.csv')
df.head()

         Date       Open       High        Low      Close  Adj Close    Volume
0  2020-10-13  48.279999  48.320000  46.990002  47.000000  47.000000   9805900
1  2020-10-14  47.490002  47.700001  45.619999  45.980000  45.980000  14449000
2  2020-10-15  45.060001  46.090000  44.299999  46.029999  46.029999  19823800
3  2020-10-16  46.360001  46.450001  45.049999  45.810001  45.810001  13005300
4  2020-10-19  46.049999  46.299999  45.240002  45.820000  45.820000   9870700

In [6]:
df = pd.read_csv('C://Users//aksha//Desktop//Projects//SINS_PROJECT//dataset//TWTR.csv')
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
247,2021-10-06,58.950001,61.709999,58.790001,61.290001,61.290001,10648100
248,2021-10-07,62.200001,64.360001,62.150002,63.970001,63.970001,15010400
249,2021-10-08,64.250000,64.339996,63.310001,63.680000,63.680000,8094900
250,2021-10-11,62.990002,63.509998,62.070000,62.099998,62.099998,9020400
251,2021-10-12,61.680000,62.799999,60.790001,61.450001,61.450001,9941400

In [3]:
df = pd.read_csv('C://Users//aksha//Desktop//Projects//SINS_PROJECT//dataset//TSLA.csv')
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2020-10-13,443.350006,448.890015,436.600006,446.649994,446.649994,34463700
1,2020-10-14,449.779999,465.899994,447.350006,461.299988,461.299988,47879700
2,2020-10-15,450.309998,456.570007,442.500000,448.880005,448.880005,35672400
3,2020-10-16,454.440002,455.950012,438.850006,439.670013,439.670013,32775900
4,2020-10-19,446.239990,447.000000,428.869995,430.829987,430.829987,36287800

In [4]:
df = pd.read_csv('C://Users//aksha//Desktop//Projects//SINS_PROJECT//dataset//TSLA.csv')
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
247,2021-10-06,776.200012,786.659973,773.219971,782.750000,782.750000,14632800
248,2021-10-07,785.460022,805.000000,783.380005,793.609985,793.609985,19195800
249,2021-10-08,796.210022,796.380005,780.909973,785.489990,785.489990,16711100
250,2021-10-11,787.650024,801.239990,785.500000,791.940002,791.940002,14200300
251,2021-10-12,800.929993,812.320007,796.570007,805.719971,805.719971,21978700